<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>PromiseSolving</title>
    <script src="../js/funciones.js" charset="utf-8"></script>
      </head>
  <body>
    <h1>PromiseSolving</h1>
    <script type="text/javascript">
  try {
       const myPromise = new Promise( ( resolve, reject ) => {
      console.log( 'Starting asynchronous work!' );

       setTimeout( () => { resolve( 'Done!' ); }, 0 );
       reject( new Error 'Promise was resolved!' );
      } );

      myPromise.then( value => console.log( value ) );
      myPromise.catch( err => console.log( err ) );
 Snippet 2.22: Promise rejection wi
      myPromse.finally( value => {
       console.log( 'Finally!' );
       } );
}catch ( err ) {
 console.log( "Got error:"+ err.message );
}

</script>
</body>
</html>
